-- Mega-Sena Draws Table
CREATE TABLE IF NOT EXISTS draws (
  id INTEGER PRIMARY KEY,
  contest_number INTEGER UNIQUE NOT NULL,
  draw_date TEXT NOT NULL,
  number_1 INTEGER NOT NULL CHECK(number_1 BETWEEN 1 AND 60),
  number_2 INTEGER NOT NULL CHECK(number_2 BETWEEN 1 AND 60),
  number_3 INTEGER NOT NULL CHECK(number_3 BETWEEN 1 AND 60),
  number_4 INTEGER NOT NULL CHECK(number_4 BETWEEN 1 AND 60),
  number_5 INTEGER NOT NULL CHECK(number_5 BETWEEN 1 AND 60),
  number_6 INTEGER NOT NULL CHECK(number_6 BETWEEN 1 AND 60),
  prize_sena REAL,
  winners_sena INTEGER DEFAULT 0,
  prize_quina REAL,
  winners_quina INTEGER DEFAULT 0,
  prize_quadra REAL,
  winners_quadra INTEGER DEFAULT 0,
  total_collection REAL,
  accumulated BOOLEAN DEFAULT 0,
  accumulated_value REAL DEFAULT 0,
  next_estimated_prize REAL,
  special_draw BOOLEAN DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_draws_contest_number ON draws(contest_number);
CREATE INDEX idx_draws_draw_date ON draws(draw_date);

-- Number Frequency Cache Table
CREATE TABLE IF NOT EXISTS number_frequency (
  number INTEGER PRIMARY KEY CHECK(number BETWEEN 1 AND 60),
  frequency INTEGER DEFAULT 0,
  last_drawn_contest INTEGER,
  last_drawn_date TEXT,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Initialize frequency table with all numbers
INSERT INTO number_frequency (number)
SELECT DISTINCT value FROM (
  SELECT 1 as value UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
  SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
  SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
  SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
  SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
  SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
  SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION
  SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION
  SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION
  SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION
  SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION
  SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60
) WHERE NOT EXISTS (SELECT 1 FROM number_frequency);

-- User Bets Table (for future tracking)
CREATE TABLE IF NOT EXISTS user_bets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bet_numbers TEXT NOT NULL,
  bet_date TEXT DEFAULT CURRENT_TIMESTAMP,
  contest_number INTEGER,
  strategy TEXT,
  cost REAL,
  result TEXT,
  hits INTEGER,
  prize_won REAL DEFAULT 0,
  notes TEXT
);

CREATE INDEX idx_user_bets_contest ON user_bets(contest_number);
CREATE INDEX idx_user_bets_date ON user_bets(bet_date);

