/**
 * JSON-LD Schema Generators for SEO
 * Following Schema.org specifications and Google's structured data guidelines.
 *
 * Site-wide nodes carry stable `@id`s so page-level nodes can reference the
 * publisher and website instead of repeating them.
 */

import { APP_INFO, BASE_URL as baseUrl } from '@/lib/constants';
import { absoluteUrl } from '@/lib/seo/metadata';

export const ORGANIZATION_ID = `${baseUrl}/#organization`;
export const WEBSITE_ID = `${baseUrl}/#website`;
const CAIXA_RESULTS_URL = 'https://loterias.caixa.gov.br/Paginas/Mega-Sena.aspx';

export interface BreadcrumbItem {
  name: string;
  url: string;
}

/** One schema.org node, serialized as JSON-LD. */
export type JsonLdNode = Record<string, unknown>;

/**
 * Organization schema - establishes site identity.
 * The logo is the 180×180 PNG generated by app/apple-icon.tsx (Google requires ≥112px).
 */
export function generateOrganizationSchema(): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': ORGANIZATION_ID,
    name: APP_INFO.NAME,
    url: baseUrl,
    logo: {
      '@type': 'ImageObject',
      url: `${baseUrl}/apple-icon`,
      width: 180,
      height: 180,
    },
    description: 'Análise estatística e arquivo histórico de resultados da Mega-Sena',
    foundingDate: '2025',
  };
}

/**
 * WebApplication schema - describes the lottery analyzer tool
 */
export function generateWebApplicationSchema(): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    '@id': `${baseUrl}/#app`,
    name: APP_INFO.NAME,
    url: baseUrl,
    applicationCategory: 'UtilitiesApplication',
    operatingSystem: 'All',
    isAccessibleForFree: true,
    inLanguage: 'pt-BR',
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'BRL',
    },
    description:
      'Ferramenta gratuita de análise estatística da Mega-Sena com resultados de todos os concursos, frequência de cada número, padrões históricos e gerador de apostas por orçamento.',
    featureList: [
      'Resultado de cada concurso desde 1996',
      'Frequência e atraso de cada número de 1 a 60',
      'Análise de padrões históricos',
      'Gerador de apostas por orçamento',
    ],
    browserRequirements: 'Requires JavaScript. Requires HTML5.',
    softwareVersion: APP_INFO.VERSION,
    publisher: { '@id': ORGANIZATION_ID },
  };
}

/**
 * WebSite schema - the node every page's WebPage points to via `isPartOf`.
 */
export function generateWebSiteSchema(): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': WEBSITE_ID,
    name: APP_INFO.NAME,
    url: baseUrl,
    description: 'Resultados, estatísticas e gerador de apostas da Mega-Sena',
    inLanguage: 'pt-BR',
    publisher: { '@id': ORGANIZATION_ID },
  };
}

/**
 * BreadcrumbList schema - navigation path.
 * Pass `path` to give the list a stable `@id` that the page node can reference.
 */
export function generateBreadcrumbSchema(items: BreadcrumbItem[], path?: string): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    ...(path ? { '@id': `${absoluteUrl(path)}#breadcrumb` } : {}),
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      item: item.url.startsWith('http') ? item.url : absoluteUrl(item.url),
    })),
  };
}

interface WebPageSchemaInput {
  path: string;
  name: string;
  description: string;
  type?: 'WebPage' | 'CollectionPage';
  datePublished?: string;
  dateModified?: string;
  hasBreadcrumb?: boolean;
}

/**
 * WebPage / CollectionPage node for a single page, linked to the site graph.
 */
export function generateWebPageSchema({
  path,
  name,
  description,
  type = 'WebPage',
  datePublished,
  dateModified,
  hasBreadcrumb = true,
}: WebPageSchemaInput): JsonLdNode {
  const url = absoluteUrl(path);
  return {
    '@context': 'https://schema.org',
    '@type': type,
    '@id': `${url}#webpage`,
    url,
    name,
    description,
    inLanguage: 'pt-BR',
    isPartOf: { '@id': WEBSITE_ID },
    publisher: { '@id': ORGANIZATION_ID },
    ...(hasBreadcrumb ? { breadcrumb: { '@id': `${url}#breadcrumb` } } : {}),
    ...(datePublished ? { datePublished } : {}),
    ...(dateModified ? { dateModified } : {}),
  };
}

interface DatasetSchemaInput {
  path: string;
  totalDraws: number;
  firstDrawDate: string;
  lastDrawDate: string;
  /** When the data last changed (load or correction), not the last draw date. */
  dateModified: string | null;
}

/**
 * Dataset schema for the results archive (read by Google Dataset Search).
 * No `license` is declared: the draws are CAIXA's public results and this site
 * does not own a license to grant for them.
 */
export function generateResultsDatasetSchema({
  path,
  totalDraws,
  firstDrawDate,
  lastDrawDate,
  dateModified,
}: DatasetSchemaInput): JsonLdNode {
  const url = absoluteUrl(path);
  return {
    '@context': 'https://schema.org',
    '@type': 'Dataset',
    '@id': `${url}#dataset`,
    name: 'Resultados históricos da Mega-Sena',
    description: `Resultados dos ${totalDraws.toLocaleString('pt-BR')} concursos da Mega-Sena registrados no arquivo, com dezenas sorteadas, data do sorteio, número de apostas ganhadoras e prêmio por aposta na sena, quina e quadra, arrecadação e valor acumulado, conforme publicados pela CAIXA Econômica Federal.`,
    url,
    inLanguage: 'pt-BR',
    isAccessibleForFree: true,
    creator: { '@id': ORGANIZATION_ID },
    isBasedOn: CAIXA_RESULTS_URL,
    temporalCoverage: `${firstDrawDate}/${lastDrawDate}`,
    spatialCoverage: { '@type': 'Place', name: 'Brasil' },
    ...(dateModified ? { dateModified } : {}),
    keywords: ['Mega-Sena', 'loteria', 'resultados', 'CAIXA', 'dezenas sorteadas'],
    variableMeasured: [
      'Dezenas sorteadas',
      'Data do sorteio',
      'Apostas ganhadoras por faixa',
      'Prêmio por aposta ganhadora',
      'Valor acumulado',
    ],
  };
}

/**
 * FAQPage schema. Google no longer shows FAQ rich results, but other engines
 * and assistants still parse the markup; keep it only where the FAQ is visible.
 */
export function generateFAQSchema(
  faqs: ReadonlyArray<{ question: string; answer: string }>
): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  };
}
